version: "3.9"

services:
  nginx:
    image: nginx:1.29.2
    container_name: nginx
    ports:
      - "8080:80"                         # single public entry point
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_blue
      - app_green

  app_blue:
    image: ${BLUE_IMAGE:-yimikaade/wonderful:devops-stage-two}
    platform: linux/amd64
    container_name: app_blue
    environment:
      RELEASE_ID: ${RELEASE_ID_BLUE:-blue-v1.0.0}
      APP_POOL: blue
      PORT: ${PORT:-3000}
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/healthz"]
      interval: 3s
      timeout: 1s
      retries: 5

  app_green:
    image: ${GREEN_IMAGE:-yimikaade/wonderful:devops-stage-two}
    platform: linux/amd64
    container_name: app_green
    environment:
      RELEASE_ID: ${RELEASE_ID_GREEN:-green-v1.0.0}
      APP_POOL: green
      PORT: ${PORT:-3000}
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/healthz"]
      interval: 3s
      timeout: 1s
      retries: 5

